require("personal.modes")
require("personal.statusbar")
require("config.options")
require("config.lazy")
require("config.keymaps")
require("config.netrw")
require("config.post-start")
require("personal.autorun")
